/** @type {import('@remix-run/dev').AppConfig} */
export default {
  ignoredRouteFiles: ['**/.*'],
  // These are dependencies that should be bundled with the server
  serverDependenciesToBundle: ['drizzle-orm', 'kysely'],
  // These are native dependencies that should be external
  serverDependencies: [
    'pg',
    'pg/**/*',
    'mysql2',
    'mysql2/**/*',
    'mysql2/promise',
    'better-sqlite3',
    'better-sqlite3/**/*',
    'drizzle-orm/node-postgres',
    'drizzle-orm/mysql2',
    'drizzle-orm/better-sqlite3',
    'drizzle-orm/better-sqlite3/**/*',
  ],
  serverModuleFormat: 'esm',
  browserNodeBuiltinsPolyfill: {
    modules: {
      events: true,
      crypto: true,
      dns: true,
      fs: true,
      net: true,
      tls: true,
      path: true,
      stream: true,
      string_decoder: true,
      util: true,
      'node:events': true,
      process: true,
      timers: true,
      buffer: true,
      zlib: true,
      url: true,
    },
  },
  serverBuildPath: 'build/index.js',
  serverMinify: false,
  serverPlatform: 'node',
  serverMainFields: ['module', 'main'],
  assetsBuildDirectory: 'public/build',
  publicPath: '/build/',
  watchPaths: [],
  future: {
    v2_dev: true,
    v2_errorBoundary: true,
    v2_headers: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
};
